name: easy_shared_preferences_example
description: "Demonstrates how to use the easy_shared_preferences plugin."
publish_to: 'none'
environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  easy_shared_preferences:
    path: ../
  cupertino_icons: ^1.0.8
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
